### ISSUE TITLE
Craft4 version? 

### ISSUE THREAD

**Issue by timbertens** [statikbe/craft-hiddentab#2]
Are you considering a Craft 4 compatible version of this handy plugin ?

**Comment by janhenckens** [comment]
Hey @timbertens, this was a bit of an example plugin for a new developer a couple of years ago, not something we actively use.

But as it happens we have a couple of new people in house right now, for which this would be a good learning opportunity as well. I'll check if they want to have a go at it :)

**Comment by HannahDeWachter** [comment]
Hi @timbertens,
You can use Craft 4's conditions to hide tabs. The tabs of an entry type has settings where you can set conditions.
So this plugin is not needed anymore in Craft 4
